#if EXAMPLE
#endif

#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

using System.Text.Json.Serialization;

/*
{
    "klantId": 5,
    "naam": "Anna de Vries",
    "adres": "Brugstraat 15, 5000 IJ Eindhoven",
    "telefoon": "0612345682",
    "email": "anna.de.vries@example.com",
    "bestellingens": [],
    "voertuigens": []
  }
 */

namespace Assignment.Api.Client
{
    // <auto-generated />
    //
    // To parse this JSON data, add NuGet 'System.Text.Json' then do:
    //
    //    using QuickType;
    //
    //    var welcome = Welcome.FromJson(jsonString);

    public partial class Klant
        {
            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyName("klantId")]
            public long? KlantId { get; set; }

            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyName("naam")]
            public string Naam { get; set; }

            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyName("adres")]
            public string Adres { get; set; }

            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyName("telefoon")]
            public string Telefoon { get; set; }

            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyName("email")]
            public string Email { get; set; }

            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyName("bestellingens")]
            public List<object> Bestellingens { get; set; }

            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyName("voertuigens")]
            public List<object> Voertuigens { get; set; }
        }
}
